### PR TITLE
Add installation script in javascript

### LINKED ISSUE #48: Use Javascript instead of a shell script for npm install

### PR DESCRIPTION
**Pull request by sowmiyamuthuraman**
Fixes #48

### CODE REVIEW

**Review by RedMser — APPROVED** [review]
Thanks for your contribution! :D
While we found some issues looking through your code, I've decided to fix them myself for the merge.

**Comment by sowmiyamuthuraman** [comment]
> Thanks for your contribution! :D
> While we found some issues looking through your code, I've decided to fix them myself for the merge.
Can you please point me the issues?

**Comment by RedMser** [comment]
> Can you please point me the issues?

I just pushed the fixes on your PR, you can see for yourself what I changed.

It was mainly the indentation and general code style was not in line with the project (although to be fair, we don't have any guidelines defined yet, so I can't blame you! :sweat_smile: )

I also took the opportunity to solve some issues that I couldn't get working inside of the shell script version.

**Comment by sowmiyamuthuraman** [comment]
> > Can you please point me the issues?
> 
> I just pushed the fixes on your PR, you can see for yourself what I changed.
> 
> It was mainly the indentation and general code style was not in line with the project (although to be fair, we don't have any guidelines defined yet, so I can't blame you!  )
> 
> I also took the opportunity to solve some issues that I couldn't get working inside of the shell script version.

I didn't notice the commits. Thanks @RedMser

**Pull request merged**
