### PR TITLE
Create images for Installation wiki page

### PR DESCRIPTION
**Pull request by RedMser**
Working on #50 

Also fix issue with install script which I noticed while working on the docs.

### CODE REVIEW

**Review by g-wizzy — DISMISSED** [review]
I'd love the signage on the pictures to be a bit cleaner if you don't mind.

**Comment by RedMser** [comment]
> I'd love the signage on the pictures to be a bit cleaner if you don't mind.

The wiki page will have a full description of each picture, but I didn't upload that yet (else the wiki would have missing images, without this branch merged).
Check it here https://gist.github.com/RedMser/07219462890f0c62c8470fc379f20782

**Comment by g-wizzy** [comment]
I meant that the red arrows and such in the images should probably not be hand drawn

**Comment by RedMser** [comment]
> I meant that the red arrows and such in the images should probably not be hand drawn

Oh, I read "clearer" not "cleaner". Fair enough.
I'm no graphics designer, I'll let @Blatoy handle it xd

**Review by Blatoy — APPROVED** [review]

**Pull request merged**
